# -*- coding: utf-8 -*-
"""Assignment of AIClass05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IqE-PUH2RyKSauz2-qPAo5vp1vpnBik9
"""

# Assignment - Create a calculator (+ - * /) with using return function

# Define functions with return
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Error! Division by zero."
    return a / b

def calculator():
    while True:  # loop until user quits
        print("\n--- TJ's Simple Calculator ---")
        print("Enter 'q' at any time to quit.")

        first_input = input("Enter first number: ")
        if first_input.lower() == 'q':
            print("Exiting Calculator. Goodbye!")
            break

        operator = input("Enter operator (+, -, *, /): ")
        if operator.lower() == 'q':
            print("Exiting Calculator. Goodbye!")
            break

        second_input = input("Enter second number: ")
        if second_input.lower() == 'q':
            print("Exiting Calculator. Goodbye!")
            break

        # Convert inputs to float
        num1 = float(first_input)
        num2 = float(second_input)

        # Perform calculation
        if operator == '+':
            result = add(num1, num2)
        elif operator == '-':
            result = subtract(num1, num2)
        elif operator == '*':
            result = multiply(num1, num2)
        elif operator == '/':
            result = divide(num1, num2)
        else:
            result = "Invalid operator!"

        print("Result:", result)

# Run calculator
calculator()