# -*- coding: utf-8 -*-
"""Assignment of AIClass02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUiAsF7L9U7W6Awrwd4Q1Y8jkZElGV_k
"""

# Q1: Variables & Data Types
#1. Create the following variables:
#○ name → your full name
#○ age → your age
#○ is_student → a boolean value (True/False)

a = "Full Name: Taha Jalal" #Full Name
print(a)

b = "Age: 33" #Age
print(b)

c = "is_student: True" #boolean value
print(c)

#2. Print all variables inone line.
Name = "Taha Jalal"
Age = "33"
is_student = True
print(name,",",age,",",is_student)

#3. Print the data type of each variable using type().
name_type = type(name)
print(name_type)
age_type = type(age)
print(age_type)
boolean_type = type(is_student)
print(boolean_type)

#Q2: Arithmetic Operators
#Let x = 20 and y = 6.
x = 20
y = 6

#Perform and print the results of:
# Addition
print(x+y)

# Subtraction
print(x-y)

# Multiplication
print(x*y)

# Division
print(x/y)

# Floor Division
print(x//y)

# Modulus
print(x%y)

# Exponent
print(x**y)

#Q3: Assignment Operators
#Let num = 10.
num1 = 10
a = num1

#1. Add 5 to num using the += operator.
num2 = a+5
print(num2)

#2. Multiply num by 2 using the *= operator.
num3 = a*2
print(num3)

#3. Subtract 4 from num using the -= operator.
num4 = a-4
print(num4)

#4. Print the final value of num.
num = (((num1+num2)*num3)-num4)
print(num)

#Q4: Comparison Operators
#Take a = 15 and b = 12.
a = 15
b = 12

#Check and print the results of the following comparisons:
# a > b
print(a > b)

# a < b
print(a < b)

# a == b
print(a == b)

# a != b
print(a != b)

# a >= b
print(a >= b)

# a <= b
print(a <= b)

#Q5: Logical Operators
#Let p = True and q = False.
p = True
q = False
#Check and print the result of:

# p and q
result = p and q
print(result)

# p or q
result = p or q
print(result)

# not p
result = not p
print(result)

# not q
result = not q
print(result)

#Q6: Real-Life Example
#The price of one notebook is 80 rupees.
#If you buy 7 notebooks, calculate the total price.

a = "The price of one notebook is 80 rupees."
print(a)

unitprice = 80
x = unitprice

b = "I bought 7 notebooks"
print(b)

buy = 7
y = buy

total_price = x*y
z = total_price

print("Total Price of the Notebooks:",z)

#If you have 600 rupees, check (using comparison operator) whether your money is
#enough to buy them or not.
#Print the result in a clear message.

money = 600
c = money
print("Do I have enough money to buy 7 notebooks?", c >=(z))

#Q7: Bonus (Optional)
#Take two numbers as input from the user.
num1 = 30
x = num1

num2 = 45
y = num2
#Print their sum.
print("num1 is", x)
print("num2 is", y)
print("num1 added by num2", "=", x+y)

#Print whether the first number is greater than the second number or not
print("Is num1 greater than num2?",x > y)